const SEARCH_ITEMS = 'SEARCH_ITEMS';
const UPDATE_SEARCH_INPUT = 'UPDATE_SEARCH_INPUT';
const ADD_TO_CART = 'ADD_TO_CART';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
const TOGGLE_QUANTITY = 'TOGGLE_QUANTITY';
const OPEN_MODAL = 'OPEN_MODAL';
const CLOSE_MODAL = 'CLOSE_MODAL';
const GET_TOTALS = 'GET_TOTALS'

export { SEARCH_ITEMS, UPDATE_SEARCH_INPUT, ADD_TO_CART, REMOVE_FROM_CART, TOGGLE_QUANTITY, OPEN_MODAL, CLOSE_MODAL, GET_TOTALS };